version: "3.9"

services:
  postgres:
      image: postgres
      environment:
        - POSTGRES_DB=brewkit
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgrespw
      ports:
        - "5432:5432"
      volumes:
        - ./dir:/var/lib/postgresql/data